var series = [
    {   
        name: "1. Beers",
        price: "ETH",
        item1: "./images/Coming.png",
        link1: "#0",
        id1: "#1",
        item2: "./images/Coming.png",
        link2: "#0",
        id2: "#2",
        item3: "./images/Coming.png",
        link3: "#0",
        id3: "#3",
        item4: "./images/Coming.png",
        link4: "#0",
        id4: "#4",
        item5: "./images/Coming.png",
        link5: "#0",
        id5: "#5",
    },
    {   
        name: "2. Psycachaças",
        price: "0.1 ETH",
        item1: "./images/Psycachazas/Psycachaza1.png",
        link1: "#0",
        id1: "#6",
        item2: "./images/Coming.png",
        link2: "#0",
        id2: "#7",
        item3: "./images/Coming.png",
        link3: "#0",
        id3: "#8",
        item4: "./images/Coming.png",
        link4: "#0",
        id4: "#9",
        item5: "./images/Coming.png",
        link5: "#0",
        id5: "#10",
    },
    {   
        name: "3. Frutilocas",
        price: "0.1 ETH",
        item1: "./images/Frutilocas/Frutiloca1.png",
        link1: "#0",
        id1: "#11",
        item2: "./images/Coming.png",
        link2: "#0",
        id2: "#12",
        item3: "./images/Coming.png",
        link3: "#0",
        id3: "#13",
        item4: "./images/Coming.png",
        link4: "#0",
        id4: "#14",
        item5: "./images/Coming.png",
        link5: "#0",
        id5: "#15",
    },
    {   
        name: "4. Psytinis",
        price: "0.1 ETH",
        item1: "./images/Psytinis/Psytini1.png",
        link1: "#0",
        id1: "#16",
        item2: "./images/Coming.png",
        link2: "#0",
        id2: "#17",
        item3: "./images/Coming.png",
        link3: "#0",
        id3: "#18",
        item4: "./images/Coming.png",
        link4: "#0",
        id4: "#19",
        item5: "./images/Coming.png",
        link5: "#0",
        id5: "#20",
    },
    {   
        name: "5. Frozens",
        price: "ETH",
        item1: "./images/Coming.png",
        link1: "#0",
        id1: "#21",
        item2: "./images/Coming.png",
        link2: "#0",
        id2: "#22",
        item3: "./images/Coming.png",
        link3: "#0",
        id3: "#23",
        item4: "./images/Coming.png",
        link4: "#0",
        id4: "#24",
        item5: "./images/Coming.png",
        link5: "#0",
        id5: "#25",
    },
    {   
        name: "6. Sweet dreams",
        price: "ETH",
        item1: "./images/Coming.png",
        link1: "#0",
        id1: "#26",
        item2: "./images/Coming.png",
        link2: "#0",
        id2: "#27",
        item3: "./images/Coming.png",
        link3: "#0",
        id3: "#28",
        item4: "./images/Coming.png",
        link4: "#0",
        id4: "#29",
        item5: "./images/Coming.png",
        link5: "#0",
        id5: "#30",
    },
    {   
        name: "7. Psyshots",
        price: "ETH",
        item1: "./images/Coming.png",
        link1: "#0",
        id1: "#31",
        item2: "./images/Coming.png",
        link2: "#0",
        id2: "#32",
        item3: "./images/Coming.png",
        link3: "#0",
        id3: "#33",
        item4: "./images/Coming.png",
        link4: "#0",
        id4: "#34",
        item5: "./images/Coming.png",
        link5: "#0",
        id5: "#35",
    },
    {   
        name: "8. Tikis",
        price: "ETH",
        item1: "./images/Coming.png",
        link1: "#0",
        id1: "#36",
        item2: "./images/Coming.png",
        link2: "#0",
        id2: "#37",
        item3: "./images/Coming.png",
        link3: "#0",
        id3: "#38",
        item4: "./images/Coming.png",
        link4: "#0",
        id4: "#39",
        item5: "./images/Coming.png",
        link5: "#0",
        id5: "#40",
    },
    {   
        name: "9. Earth classics (Occ)",
        price: "ETH",
        item1: "./images/Coming.png",
        link1: "#0",
        id1: "#41",
        item2: "./images/Coming.png",
        link2: "#0",
        id2: "#42",
        item3: "./images/Coming.png",
        link3: "#0",
        id3: "#43",
        item4: "./images/Coming.png",
        link4: "#0",
        id4: "#44",
        item5: "./images/Coming.png",
        link5: "#0",
        id5: "#45",
    },
    {   
        name: "10. Earth classics (Or)",
        price: "ETH",
        item1: "./images/Coming.png",
        link1: "#0",
        id1: "#46",
        item2: "./images/Coming.png",
        link2: "#0",
        id2: "#47",
        item3: "./images/Coming.png",
        link3: "#0",
        id3: "#48",
        item4: "./images/Coming.png",
        link4: "#0",
        id4: "#49",
        item5: "./images/Coming.png",
        link5: "#0",
        id5: "#50",
    },
    {   
        name: "11. Film classics",
        price: "ETH",
        item1: "./images/Coming.png",
        link1: "#0",
        id1: "#51",
        item2: "./images/Coming.png",
        link2: "#0",
        id2: "#52",
        item3: "./images/Coming.png",
        link3: "#0",
        id3: "#53",
        item4: "./images/Coming.png",
        link4: "#0",
        id4: "#54",
        item5: "./images/Coming.png",
        link5: "#0",
        id5: "#55",
    },
    {   
        name: "12. Art classics",
        price: "ETH",
        item1: "./images/Coming.png",
        link1: "#0",
        id1: "#56",
        item2: "./images/Coming.png",
        link2: "#0",
        id2: "#57",
        item3: "./images/Coming.png",
        link3: "#0",
        id3: "#58",
        item4: "./images/Coming.png",
        link4: "#0",
        id4: "#59",
        item5: "./images/Coming.png",
        link5: "#0",
        id5: "#60",
    },
    {   
        name: "13. Only for psychos",
        price: "ETH",
        item1: "./images/Coming.png",
        link1: "#0",
        id1: "#61",
        item2: "./images/Coming.png",
        link2: "#0",
        id2: "#62",
        item3: "./images/Coming.png",
        link3: "#0",
        id3: "#63",
        item4: "./images/Coming.png",
        link4: "#0",
        id4: "#64",
        item5: "./images/Coming.png",
        link5: "#0",
        id5: "#65",
    },
    {   
        name: "14. Underworld classics",
        price: "ETH",
        item1: "./images/Coming.png",
        link1: "#0",
        id1: "#66",
        item2: "./images/Coming.png",
        link2: "#0",
        id2: "#67",
        item3: "./images/Coming.png",
        link3: "#0",
        id3: "#68",
        item4: "./images/Coming.png",
        link4: "#0",
        id4: "#69",
        item5: "./images/Coming.png",
        link5: "#0",
        id5: "#70",
    },
    {   
        name: "15. Crypto classics",
        price: "ETH",
        item1: "./images/Coming.png",
        link1: "#0",
        id1: "#71",
        item2: "./images/Coming.png",
        link2: "#0",
        id2: "#72",
        item3: "./images/Coming.png",
        link3: "#0",
        id3: "#73",
        item4: "./images/Coming.png",
        link4: "#0",
        id4: "#74",
        item5: "./images/Coming.png",
        link5: "#0",
        id5: "#75",
    },
    {   
        name: "16. Bonus: Shishas",
        price: "ETH",
        item1: "./images/Coming.png",
        link1: "#0",
        id1: "#76",
        item2: "./images/Coming.png",
        link2: "#0",
        id2: "#77",
        item3: "./images/Coming.png",
        link3: "#0",
        id3: "#78",
        item4: "./images/Coming.png",
        link4: "#0",
        id4: "#79",
        item5: "./images/Coming.png",
        link5: "#0",
        id5: "#80",
    },
]
