var series = [
    {   
        name: "1. Psychirinhas",
        price: "0.1 ETH",
        item1: "./images/Psychirinhas/Psychirinha1.png",
        link1: "#0",
        id1: "#1",
        item2: "./images/Coming.png",
        link2: "#0",
        id2: "#2",
        item3: "./images/Coming.png",
        link3: "#0",
        id3: "#3",
        item4: "./images/Coming.png",
        link4: "#0",
        id4: "#4",
        item5: "./images/Coming.png",
        link5: "#0",
        id5: "#5",
    },
    {   
        name: "2. Psytinis",
        price: "0.1 ETH",
        item1: "./images/Psytinis/Psytini1.png",
        link1: "#0",
        id1: "#6",
        item2: "./images/Coming.png",
        link2: "#0",
        id2: "#7",
        item3: "./images/Coming.png",
        link3: "#0",
        id3: "#8",
        item4: "./images/Coming.png",
        link4: "#0",
        id4: "#9",
        item5: "./images/Coming.png",
        link5: "#0",
        id5: "#10",
    },
    {   
        name: "3. Fruity",
        price: "0.1 ETH",
        item1: "./images/Fruity/Fruity1.png",
        link1: "#0",
        id1: "#11",
        item2: "./images/Coming.png",
        link2: "#0",
        id2: "#12",
        item3: "./images/Coming.png",
        link3: "#0",
        id3: "#13",
        item4: "./images/Coming.png",
        link4: "#0",
        id4: "#14",
        item5: "./images/Coming.png",
        link5: "#0",
        id5: "#15",
    }
]
